install and config ngnix on my sever

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,22 +1,33 @@
 #!/usr/bin/env bash
-# install and config ngnix in my sever
+#install ngix and put holberton inside
 
-apt-get update -y
-apt-get install -y nginx
-service nginx start
-echo "server {
-    listen 80;
-    listen [::]:80;
-
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
     root /var/www/html;
     index index.html;
-
-    server_name localhost;
-
-    location / {
-        try_files $uri $uri/ =404;
-        add_header Content-Type "text/html";
-        return 200 "Hello World!";
+    server {
+        listen 80;
+        location \ {
+        }
     }
-}" > /etc/nginx/sites-available/default
-service nginx restart
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/html
+    echo "hello Holberton School" > \
+	/var/www/html/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
